name: SBT CI Build

on:
  push:
    branches: [ series/7.x ]
  pull_request:
    branches: [ series/7.x ]

jobs:
  scala_2_12:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'adopt'
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt ++2.12.20 test
      
  scala_2_13:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'adopt'
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt ++2.13.15 test

  scala_3:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        run: sbt ++3.3.0 test
